
<div dir="rtl" style="text-align: right;">

 یه سری داده داریم با استفاده از سه روش مختلف، ضرایب مدل رگرسیون خطی و لیبل ها را محاسبه کنیم.
این سه روش عبارتند از:

1.
روش شبه معکوس (Pseudo-Inverse Method): در این روش، شبه معکوس ماتریس ویژگیها محاسبه شده و سپس ضرایب مدل و لیبل ها به دست می آیند.

2.
روش ضرب ماتریسها (Matrix Multiplication Method): در این روش، ضرایب مدل با استفاده از ضرب ماتریسها محاسبه شده و سپس لیبل ها به دست می آیند.

3.
روش تجزیه مقدار منفرد (SVD Method): در این روش، تجزیه مقدار منفرد (SVD) بر روی ماتریس ویژگیها انجام شده و سپس ضرایب مدل و لیبل ها به دست می آیند.
</div>


In [45]:
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler
from numpy.linalg import svd

In [46]:
#  دادهها
x = np.array([
[1, 1, 0, 0, 0, 0],
[1, 1, 0, 0, 0, 0],
[1, 1, 0, 0, 0, 0],
[1, 1, 0, 0, 0, 0],
[1, 1, 0, 0, 0, 0],
[1, 0, 1, 0, 0, 0],
[1, 0, 1, 0, 0, 0],
[1, 0, 1, 0, 0, 0],
[1, 0, 1, 0, 0, 0],
[1, 0, 1, 0, 0, 0],
[1, 0, 0, 1, 0, 0],
[1, 0, 0, 1, 0, 0],
[1, 0, 0, 1, 0, 0],
[1, 0, 0, 1, 0, 0],
[1, 0, 0, 1, 0, 0],
[1, 0, 0, 0, 1, 0],
[1, 0, 0, 0, 1, 0],
[1, 0, 0, 0, 1, 0],
[1, 0, 0, 0, 1, 0],
[1, 0, 0, 0, 1, 0],
[1, 0, 0, 0, 0, 1],
[1, 0, 0, 0, 0, 1],
[1, 0, 0, 0, 0, 1],
[1, 0, 0, 0, 0, 1],
[1, 0, 0, 0, 0, 1]
])
y = np.array([7, 12, 14, 19, 7, 7, 17, 18, 25, 10, 15, 12, 18, 22, 11, 11, 18, 19, 19, 15, 9, 18, 19, 23, 11])

# محاسبه شبه معکوس ماتریس
x_pseudo_inv = np.linalg.pinv(x)
b0 = np.dot(x_pseudo_inv, y)
yhat0 = np.dot(x, b0)

# محاسبه ضرایب با استفاده از ضرب ماتریسها
b1 = np.dot(np.linalg.pinv(np.dot(x.T, x)), np.dot(x.T, y))
yhat1 = np.dot(x, b1)

#  تجزیه مقدار منفرد (SVD)
U,S,Vt = np.linalg.svd(x, full_matrices=False)

# solve Ax = b for the best possible approximate solution in terms of least squares
b2 = Vt.T @ np.linalg.inv(np.diag(S)) @ U.T @ y

# perform train and test inference
yhat2 =x @ b2


# تجزیه مقدار منفرد (SVD) با منظمسازی
U, S, Vt = np.linalg.svd(x, full_matrices=False)
lambda_ = 1e-5  # مقدار منظمسازی
S_inv = np.diag(S / (S**2 + lambda_))
b3 = Vt.T @ S_inv @ U.T @ y

yhat3 = x @ b3

In [47]:
# ایجاد DataFrame برای نمایش ضرایب
coefficients_df = pd.DataFrame({
'Method 1 (Pseudo-inverse)': b0,
'Method 2 (Matrix Multiplication)': b1,
'Method 4 (SVD+reg)': b3,
'Method 3 (SVD)': b2,
})


coefficients_df

Method 1 (Pseudo-inverse)  Method 2 (Matrix Multiplication)  \
0                  12.533333                         12.533333   
1                  -0.733333                         -0.733333   
2                   2.866667                          2.866667   
3                   3.066667                          3.066667   
4                   3.866667                          3.866667   
5                   3.466667                          3.466667   

   Method 4 (SVD+reg)  Method 3 (SVD)  
0           12.533329    1.030921e+16  
1           -0.733328   -1.030921e+16  
2            2.866665   -1.030921e+16  
3            3.066665   -1.030921e+16  
4            3.866663   -1.030921e+16  
5            3.466664   -1.030921e+16

In [48]:
# ایجاد DataFrame برای نمایش ضرایب
yhat = pd.DataFrame({
'Method 1 (Pseudo-inverse)': yhat0,
'Method 2 (Matrix Multiplication)': yhat1,
'Method 4 (SVD+reg)': yhat3,
'Method 3 (SVD)': yhat2,
})

yhat

Method 1 (Pseudo-inverse)  Method 2 (Matrix Multiplication)  \
0                        11.8                              11.8   
1                        11.8                              11.8   
2                        11.8                              11.8   
3                        11.8                              11.8   
4                        11.8                              11.8   
5                        15.4                              15.4   
6                        15.4                              15.4   
7                        15.4                              15.4   
8                        15.4                              15.4   
9                        15.4                              15.4   
10                       15.6                              15.6   
11                       15.6                              15.6   
12                       15.6                              15.6   
13                       15.6                              15.6   
14                       15.6                              15.6   
15                       16.4                              16.4   
16                       16.4                              16.4   
17                       16.4                              16.4   
18                       16.4                              16.4   
19                       16.4                              16.4   
20                       16.0                              16.0   
21                       16.0                              16.0   
22                       16.0                              16.0   
23                       16.0                              16.0   
24                       16.0                              16.0   

    Method 4 (SVD+reg)  Method 3 (SVD)  
0            11.800001             4.0  
1            11.800001             4.0  
2            11.800001             4.0  
3            11.800001             4.0  
4            11.800001             4.0  
5            15.399994            10.0  
6            15.399994            10.0  
7            15.399994            10.0  
8            15.399994            10.0  
9            15.399994            10.0  
10           15.599994             8.0  
11           15.599994             8.0  
12           15.599994             8.0  
13           15.599994             8.0  
14           15.599994             8.0  
15           16.399992            18.0  
16           16.399992            18.0  
17           16.399992            18.0  
18           16.399992            18.0  
19           16.399992            18.0  
20           15.999993            14.0  
21           15.999993            14.0  
22           15.999993            14.0  
23           15.999993            14.0  
24           15.999993            14.0

حالا همین کار رو برای داده های کالیفرنیا انجام میدهیم

In [73]:
# بارگذاری دادهها
housing = fetch_california_housing()
x = housing.data
y = housing.target


# محاسبه شبه معکوس ماتریس
x_pseudo_inv = np.linalg.pinv(x)
b0 = np.dot(x_pseudo_inv, y)
yhat0 = np.dot(x, b0)

# محاسبه ضرایب با استفاده از ضرب ماتریسها
b1 = np.dot(np.linalg.pinv(np.dot(x.T, x)), np.dot(x.T, y))
yhat1 = np.dot(x, b1)

# # تجزیه مقدار منفرد (SVD)
U,S,Vt = np.linalg.svd(x, full_matrices=False)

# solve Ax = b for the best possible approximate solution in terms of least squares
b2 = Vt.T @ np.linalg.inv(np.diag(S)) @ U.T @ y

# perform train and test inference
yhat2 =x @ b2


In [74]:
# ایجاد جدول ضرایب
coefficients = pd.DataFrame({
'Feature              ': housing.feature_names,
'Pseudo Inverse       ': b0,
'Matrix Multiplication': b1,
'SVD                  ': b2
}).round(4)
coefficients

Feature                Pseudo Inverse         Matrix Multiplication  \
0                MedInc                 0.5135                 0.5135   
1              HouseAge                 0.0157                 0.0157   
2              AveRooms                -0.1825                -0.1825   
3             AveBedrms                 0.8651                 0.8651   
4            Population                 0.0000                 0.0000   
5              AveOccup                -0.0047                -0.0047   
6              Latitude                -0.0639                -0.0639   
7             Longitude                -0.0164                -0.0164   

   SVD                    
0                 0.5135  
1                 0.0157  
2                -0.1825  
3                 0.8651  
4                 0.0000  
5                -0.0047  
6                -0.0639  
7                -0.0164

In [75]:
# ایجاد DataFrame برای نمایش ضرایب
yhat = pd.DataFrame({
'Pseudo Inverse       ': yhat0,
'Matrix Multiplication': yhat1,
'SVD                  ': yhat2
}).round(4)

yhat

Pseudo Inverse         Matrix Multiplication  SVD                  
0                     4.0984                 4.0984                 4.0984
1                     3.8838                 3.8838                 3.8838
2                     3.5294                 3.5294                 3.5294
3                     3.1530                 3.1530                 3.1530
4                     2.1542                 2.1542                 2.1542
...                      ...                    ...                    ...
20635                 0.7058                 0.7058                 0.7058
20636                 1.0656                 1.0656                 1.0656
20637                 0.6193                 0.6193                 0.6193
20638                 0.7436                 0.7436                 0.7436
20639                 0.9905                 0.9905                 0.9905

[20640 rows x 3 columns]

In [76]:
# روش 4: استفاده از شبکه عصبی
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [77]:
# استانداردسازی دادهها
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
# ساخت مدل شبکه عصبی
model = Sequential()
model.add(Dense(64, input_dim=x_scaled.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))

# کامپایل مدل
model.compile(optimizer='adam', loss='mean_squared_error')

# تعریف Early Stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

# آموزش مدل با Early Stopping
model.fit(x_scaled, y, epochs=100, batch_size=10, validation_split=0.2, callbacks=[early_stopping], verbose=1)

# پیش بینی
yhat_nn = model.predict(x_scaled)

Epoch 1/100


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1652/1652 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1.0457 - val_loss: 0.4182
Epoch 2/100
1652/1652 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.3508 - val_loss: 0.4177
Epoch 3/100
1652/1652 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 0.3302 - val_loss: 0.5772
Epoch 4/100
1652/1652 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.3184 - val_loss: 0.4668
Epoch 5/100
1652/1652 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 0.3145 - val_loss: 0.5457
645/645 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step


In [78]:
# نمایش وزنهای لایه های شبکه عصبی
for layer in model.layers:
  weights, biases = layer.get_weights()


In [79]:
biases

array([0.1580499], dtype=float32)

In [80]:
weights

array([[ 0.42657724],
       [-0.01266061],
       [ 0.26862162],
       [ 0.41771472],
       [-0.17999823],
       [-0.30126566],
       [ 0.10072324],
       [-0.05936065],
       [-0.09866121],
       [-0.36219114],
       [-0.17502405],
       [-0.04837305],
       [-0.30692196],
       [-0.4649909 ],
       [ 0.17425168],
       [ 0.12649354],
       [ 0.3127028 ],
       [-0.19244713],
       [ 0.12893972],
       [ 0.13375641],
       [-0.1098817 ],
       [ 0.4155104 ],
       [-0.41775304],
       [-0.10119593],
       [ 0.30611995],
       [ 0.304455  ],
       [-0.34434262],
       [-0.49030226],
       [-0.38577127],
       [-0.35393503],
       [-0.11090299],
       [-0.40032226]], dtype=float32)

In [81]:
weights

array([[ 0.42657724],
       [-0.01266061],
       [ 0.26862162],
       [ 0.41771472],
       [-0.17999823],
       [-0.30126566],
       [ 0.10072324],
       [-0.05936065],
       [-0.09866121],
       [-0.36219114],
       [-0.17502405],
       [-0.04837305],
       [-0.30692196],
       [-0.4649909 ],
       [ 0.17425168],
       [ 0.12649354],
       [ 0.3127028 ],
       [-0.19244713],
       [ 0.12893972],
       [ 0.13375641],
       [-0.1098817 ],
       [ 0.4155104 ],
       [-0.41775304],
       [-0.10119593],
       [ 0.30611995],
       [ 0.304455  ],
       [-0.34434262],
       [-0.49030226],
       [-0.38577127],
       [-0.35393503],
       [-0.11090299],
       [-0.40032226]], dtype=float32)